"""The published slot-engine demo, and the promises it makes.

`docs/app/` is a built artifact that this repository commits, for the same
reason `docs/planner.html` is: it is served straight off GitHub Pages, and
the quickest way to see the slot engine should not be "clone the repo and
run Python". `python tools/build_static.py` writes it from
`tools/static_src/` and `static/css/style.css`, and refuses to write
anything at all unless `js/slots.js` and `domain/calendar_logic.py` agree
about every slot in its scenario matrix.

The cost of a committed artifact is that it goes stale, and these are what
stop that:

  * every file in docs/app/ is byte-identical to what it was built from, so
    editing the published copy by hand, or editing a source and forgetting
    to rebuild, fails here rather than sitting there quietly being a
    different program;
  * docs/app/ holds exactly the built set and nothing else, so a renamed
    file cannot live on and keep being loaded;
  * the page loads every file it references and references every file it
    loads;
  * the banner still says the three things it has to say, because the whole
    defence of publishing a page like this is that it is honest about what
    it is not -- and a promise nothing checks is a promise that goes.

None of this needs a browser. The equivalence between the port and the
Python does, and that lives in tools/build_static.py where the build can
refuse; this file is the half that can run in CI on every push.

    Rebuild with:  python tools/build_static.py
    Prove the equivalence check bites:
                   python tools/build_static.py --prove
"""
import io
import json
import os
import re
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

OUT = os.path.join(ROOT, "docs", "app")
SRC = os.path.join(ROOT, "tools", "static_src")

REBUILD = "Rebuild it: python tools/build_static.py"

# Copied from tools/static_src/ unchanged.
COPIED = ("index.html", "js/slots.js", "js/demo.js", "css/demo.css")

# Everything the build writes. Anything else in docs/app/ is left over.
EXPECTED = COPIED + ("js/scenarios.js", "css/style.css")


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def published(name):
    return read(os.path.join(OUT, name.replace("/", os.sep)))


@pytest.fixture(scope="module")
def page():
    return published("index.html")


def test_the_published_demo_exists():
    assert os.path.isdir(OUT), "docs/app/ is missing. " + REBUILD
    for name in EXPECTED:
        assert os.path.isfile(os.path.join(OUT, name.replace("/", os.sep))), (
            f"docs/app/{name} is missing. " + REBUILD)


def test_docs_app_holds_exactly_what_the_build_writes():
    """A file the build no longer writes but that is still on disk is still
    served, and still loaded if anything references it. The build prunes;
    this is what notices when somebody adds one by hand."""
    present = set()
    for here, _dirs, names in os.walk(OUT):
        for name in names:
            present.add(os.path.relpath(os.path.join(here, name), OUT)
                        .replace("\\", "/"))
    assert present == set(EXPECTED), (
        f"docs/app/ does not hold the built set.\n"
        f"  extra:   {sorted(present - set(EXPECTED))}\n"
        f"  missing: {sorted(set(EXPECTED) - present)}\n" + REBUILD)


@pytest.mark.parametrize("name", COPIED)
def test_every_copied_file_is_byte_identical_to_its_source(name):
    """The point of generating the bundle is that there is one copy of each
    of these, not two. A hand-edit here is the start of the fork."""
    assert published(name) == read(os.path.join(SRC, name.replace("/", os.sep))), (
        f"docs/app/{name} has drifted from tools/static_src/{name}. " + REBUILD)


def test_the_stylesheet_is_the_app_s_own_with_a_generated_banner():
    """So the demo looks like the rest of the site because it *is* the rest
    of the site's stylesheet, not a copy somebody keeps in step by hand."""
    theirs = read(os.path.join(ROOT, "static", "css", "style.css"))
    mine = published("css/style.css")
    assert mine.startswith("/* Generated by tools/build_static.py"), (
        "the copied stylesheet does not say it is generated, so the next "
        "person to edit it will edit the copy. " + REBUILD)
    assert mine.endswith(theirs), (
        "docs/app/css/style.css has drifted from static/css/style.css. "
        + REBUILD)


def test_the_page_loads_every_file_it_references(page):
    """A renamed asset is a 404 and a page that half works -- the stylesheet
    silently missing looks like a design decision."""
    wanted = set(re.findall(r'(?:src|href)="((?:js|css)/[\w.-]+)"', page))
    assert wanted, "the page references no local assets at all"
    missing = sorted(name for name in wanted
                     if not os.path.isfile(os.path.join(
                         OUT, name.replace("/", os.sep))))
    assert not missing, f"the page references files that are not there: {missing}"
    assets = set(EXPECTED) - {"index.html"}      # the page is not its own asset
    assert wanted == assets, (
        f"the page and the build disagree about the bundle.\n"
        f"  referenced but not built: {sorted(wanted - assets)}\n"
        f"  built but not referenced: {sorted(assets - wanted)}")


def test_the_data_is_inlined_as_javascript_not_fetched(page):
    """A fetch() of a relative URL is blocked by the file:// origin rules, so
    a JSON bundle would work on GitHub Pages and fail the moment somebody
    double-clicked index.html."""
    assert "fetch(" not in page, "the page fetches something"
    for name in ("js/slots.js", "js/demo.js"):
        assert "fetch(" not in published(name), f"{name} fetches something"
    assert 'src="js/scenarios.js"' in page, (
        "the worked examples are not loaded as a script")


def test_the_banner_says_what_this_is_not(page):
    """The whole defence of publishing this page is that it does not pretend
    to be the platform. Every clause here is load-bearing."""
    banner = re.search(r'<div class="demo-banner".*?</div>', page, re.S)
    assert banner, "the page has no banner"
    text = re.sub(r"<[^>]+>", " ", banner.group(0)).lower()
    for phrase in ("slot engine only", "not the booking platform",
                   "no account", "no database", "nothing is saved"):
        assert phrase in text, f"the banner no longer says {phrase!r}"
    assert "github.com/luke-zhang-cs-py" in banner.group(0), (
        "the banner does not link back to the repository")


def test_the_page_names_the_check_that_produced_it(page):
    """A claim of equivalence is worth something only if a reader can find
    the thing that enforces it."""
    assert "domain/calendar_logic.py" in page
    assert "tools/build_static.py" in page


def test_the_worked_examples_are_shaped_the_way_the_page_reads_them():
    """scenarios.js is generated from the build's own matrix, so every
    preset on the page is a case that was compared against the Python.
    A preset missing a field the page reads is a blank control."""
    body = published("js/scenarios.js")
    found = re.search(r"var AlmanacScenarios = (\{.*\});\s*$", body, re.S)
    assert found, "scenarios.js is not the shape the page expects"
    data = json.loads(found.group(1))

    assert data["providerId"], "no provider to ask about"
    assert len(data["presets"]) >= 5, (
        f"only {len(data['presets'])} worked examples; the interesting "
        f"cases are the point of the page")
    for preset in data["presets"]:
        for key in ("name", "note", "now", "date", "day", "duration", "data"):
            assert key in preset, f"{preset.get('name')!r} has no {key}"
        for table in ("availability", "blocked_slots", "appointments"):
            assert table in preset["data"], (
                f"{preset['name']!r} has no {table} rows, not even an empty "
                f"list -- the page would throw reading it")
        assert re.match(r"^\d{4}-\d{2}-\d{2}$", preset["date"])
        assert re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$", preset["now"]), (
            f"{preset['name']!r} pins no clock, so what it shows would "
            f"depend on the day somebody opened it")


def test_the_overview_links_to_it():
    """Published beside docs/index.html and unreachable from it is published
    to nobody."""
    overview = read(os.path.join(ROOT, "docs", "index.html"))
    assert re.search(r'href="app/?"', overview), (
        "docs/index.html does not link to the slot-engine demo, so nothing "
        "on the published site leads to it")


def test_the_port_says_where_it_cannot_follow_the_original():
    """Two languages cannot agree about int('\\u0669'), and the honest thing
    is to say which cases are excluded from the comparison rather than to
    let the build's clean run imply there are none."""
    port = published("js/slots.js")
    assert "Where the port cannot follow the original" in port, (
        "slots.js no longer states its divergences from calendar_logic.py")
    assert "calendar_logic.py" in port, "the port does not name its original"
