"""The pound ledger: the cross rate, the markup, and the ceiling.

Three things are being guarded, and only the first is ordinary CRUD.

**The arithmetic is a second implementation.** The same conversion exists in
the wallet project, and two implementations of anything drift. `rates/
cases.json` is that project's fixture, copied here whole, and the first test
below asserts this module produces its answers case for case. If either side
changes a rule, this fails rather than the two quietly disagreeing about what
a thousand dollars is worth.

**The markup divides rather than multiplies.** CIBC converts and then adds
2.5% to the Canadian figure, so buying pounds with dollars inverts that.
Taking 2.5% off the pounds is the plausible wrong answer and differs by 33p
on CA$1,000. The round-trip test is what tells the two apart, and the
shortcut is included as a negative control so the round-trip cannot pass
vacuously.

**The ledger is per user.** Nothing here reads a user id out of a payload,
and the tests check that one account cannot see or delete another's rows --
the failure that a route taking `userId` from the body would produce.
"""

import io
import json
import os

import pytest

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURE = os.path.join(HERE, "rates", "cases.json")

# A Friday, and the newest day the shipped rate file covers.
FRIDAY = "2026-09-11"
# The Sunday before it, which the ECB never publishes on.
SUNDAY = "2026-09-06"


@pytest.fixture(scope="module")
def cases():
    with io.open(FIXTURE, encoding="utf-8") as handle:
        return json.load(handle)


# ------------------------------------------------------- the shared fixture


def test_the_fixture_is_not_empty(cases):
    """A guard on the guard: a loop over nothing passes."""
    assert len(cases["cases"]) >= 40
    assert not [c for c in cases["cases"] if "error" in c]


def test_this_module_agrees_with_the_wallet_case_for_case(cases):
    """The cross-project duplication, checked.

    These answers were generated by the other implementation. Reproducing
    them here is the only thing standing between two copies of this
    arithmetic and a silent disagreement about money.
    """
    from domain import pounds

    for case in cases["cases"]:
        cad = pounds._parts(case["cadRate"])
        gbp = pounds._parts(case["gbpRate"])
        got = pounds.to_pounds(case["cadMinor"], cad, gbp)
        where = f"{case['cadMinor']} cents on {case['on']}"
        assert got["pence"] == case["poundsMinor"], where
        assert got["reference_pence"] == case["referenceMinor"], where
        assert got["fee_pence"] == case["feeMinor"], where
        assert got["cross"] == case["cross"], where


def test_the_limit_and_the_markup_match_the_wallet(cases):
    from domain import pounds
    assert pounds.LIMIT_MINOR == cases["limitMinor"]
    assert pounds.CIBC_FEE_BP == cases["feeBp"]


# ---------------------------------------------------------- the arithmetic


def test_converting_a_thousand_dollars_round_trips_back(cases):
    """If C dollars buys P pounds, then P pounds must cost C dollars again.

    The property that makes the markup's direction checkable rather than a
    matter of opinion.
    """
    from domain import pounds

    for case in cases["cases"]:
        if case["cadMinor"] < 100:
            continue        # a penny of rounding swamps a one-cent amount
        cad = pounds._parts(case["cadRate"])
        gbp = pounds._parts(case["gbpRate"])
        back = pounds.from_pounds(case["poundsMinor"], cad, gbp)
        assert abs(back - case["cadMinor"]) <= 2, (
            f"{case['cadMinor']} cents on {case['on']} came back as {back}")


def test_the_shortcut_would_not_round_trip(cases):
    """The negative control. Taking 2.5% off the pounds is the plausible
    wrong answer; if it round-tripped as well, the test above would be
    checking nothing."""
    from domain import pounds

    worst = 0
    for case in cases["cases"]:
        if case["cadMinor"] < 100:
            continue
        cad = pounds._parts(case["cadRate"])
        gbp = pounds._parts(case["gbpRate"])
        shortcut = pounds.div_half_up(
            case["referenceMinor"] * (pounds.BASIS_POINTS - pounds.CIBC_FEE_BP),
            pounds.BASIS_POINTS)
        back = pounds.from_pounds(shortcut, cad, gbp)
        worst = max(worst, abs(back - case["cadMinor"]))
    assert worst > 2, (
        "the shortcut round-trips too, so the round-trip proves nothing")


def test_rounding_goes_half_away_from_zero():
    from domain import pounds
    assert pounds.div_half_up(5, 2) == 3
    assert pounds.div_half_up(-5, 2) == -3
    with pytest.raises(pounds.PoundError):
        pounds.div_half_up(1, 0)


def test_money_says_zero_rather_than_free():
    """offerings.money says "Free" for zero, which is right for a price in a
    catalogue and wrong for a column of figures that has to line up."""
    from domain import pounds
    assert pounds.money(0) == "£0.00"
    assert pounds.money(52118) == "£521.18"
    assert pounds.money(123456789) == "£1,234,567.89"
    assert pounds.money(-5799) == "-£57.99"
    assert pounds.money(100000, "CAD") == "CA$1,000.00"


# ------------------------------------------------------------- the rates


def test_a_weekend_uses_the_last_business_day(ctx):
    """The ECB publishes on business days. A Sunday is converted at Friday's
    rate and the row says so, rather than reaching forward to Monday."""
    from domain import pounds
    got = pounds.quote(10000, SUNDAY)
    assert got["rate_date"] == "2026-09-04"
    assert got["lag_days"] == 2


def test_a_weekday_past_the_newest_rate_is_refused(ctx):
    from domain import pounds
    with pytest.raises(pounds.PoundError) as raised:
        pounds.quote(10000, "2099-01-05")       # a Monday
    assert "later than the newest rate" in str(raised.value)


def test_a_weekend_past_the_newest_rate_is_allowed(ctx):
    """Its own rate is never coming, so refusing it would leave weekend
    spending with no figure at all."""
    from domain import pounds
    newest = pounds.coverage()["newest"]
    import datetime as dt
    saturday = dt.date.fromisoformat(newest) + dt.timedelta(days=1)
    assert saturday.weekday() == 5, "this case needs a Saturday"
    got = pounds.quote(10000, saturday.isoformat())
    assert got["rate_date"] == newest


def test_a_date_that_is_not_a_date_is_refused(ctx):
    from domain import pounds
    with pytest.raises(pounds.PoundError):
        pounds.quote(10000, "the fifth")


def test_the_shipped_file_carries_both_legs(ctx):
    from domain import pounds
    cover = pounds.coverage()
    assert cover["days"] > 7000
    assert cover["oldest"] == "1999-01-04"


# ------------------------------------------------------------- the ledger


def auth_post(client, who, **payload):
    return client.post("/api/pounds", json=payload, headers=who["auth"])


def test_recording_and_listing(client, booking):
    made = auth_post(client, booking, spentOn=FRIDAY, description="Elms rent",
                     category="Housing", cadCents=62000)
    assert made.status_code == 201, made.get_json()

    body = made.get_json()
    assert body["conversion"]["cadCents"] == 62000
    assert body["conversion"]["pence"] > 0
    assert body["summary"]["spentPence"] == body["conversion"]["pence"]

    listed = client.get("/api/pounds", headers=booking["auth"]).get_json()
    assert len(listed["conversions"]) == 1
    assert listed["limitPence"] == 100000
    assert listed["remainingPence"] == 100000 - listed["spentPence"]
    assert listed["over"] is False


def test_the_pounds_are_derived_rather_than_stored(client, booking, ctx):
    """Nothing writes a pound figure to the row, so a refreshed rate file
    changes every total rather than leaving stored figures behind."""
    from core import database as db
    from domain import pounds

    auth_post(client, booking, spentOn=FRIDAY, description="Rent",
              cadCents=100000)
    row = db.query("SELECT * FROM pound_conversions", one=True)
    assert "pence" not in row and "pounds" not in row, (
        f"a pound figure was stored: {sorted(row.keys())}")
    assert row["cad_cents"] == 100000

    expected = pounds.quote(100000, FRIDAY)["pence"]
    listed = client.get("/api/pounds", headers=booking["auth"]).get_json()
    assert listed["conversions"][0]["pence"] == expected


def test_a_conversion_over_the_limit_is_refused_with_a_figure(client, booking):
    """A budget that lets you type past it is a label, not a budget -- and a
    refusal without a number is not something anyone can act on."""
    first = auth_post(client, booking, spentOn=FRIDAY, description="Rent",
                      cadCents=180000)
    assert first.status_code == 201

    over = auth_post(client, booking, spentOn=FRIDAY, description="Flights",
                     cadCents=100000)
    assert over.status_code == 400
    message = over.get_json()["error"]
    assert "limit" in message and "£" in message and "CA$" in message, message

    listed = client.get("/api/pounds", headers=booking["auth"]).get_json()
    assert len(listed["conversions"]) == 1, "the refused row was stored anyway"


def test_exactly_on_the_limit_is_allowed(client, booking, ctx):
    """1,000.00 of a 1,000 budget is spent, not overspent."""
    from domain import pounds
    cad, gbp, _on = pounds.legs(FRIDAY)
    exact = pounds.from_pounds(pounds.LIMIT_MINOR, cad, gbp)

    made = auth_post(client, booking, spentOn=FRIDAY, description="All of it",
                     cadCents=exact)
    assert made.status_code == 201, made.get_json()
    assert made.get_json()["summary"]["remainingPence"] >= 0


def test_an_empty_or_undated_conversion_is_refused(client, booking):
    for payload in ({"spentOn": FRIDAY, "description": "", "cadCents": 100},
                    {"spentOn": FRIDAY, "description": "x", "cadCents": 0},
                    {"spentOn": "", "description": "x", "cadCents": 100},
                    {"spentOn": FRIDAY, "description": "x",
                     "cadCents": "many"}):
        got = client.post("/api/pounds", json=payload,
                          headers=booking["auth"])
        assert got.status_code == 400, f"{payload} was accepted"


def test_deleting_only_your_own(client, booking, provider):
    made = auth_post(client, booking, spentOn=FRIDAY, description="Mine",
                     cadCents=5000).get_json()["conversion"]

    theirs = client.delete(f"/api/pounds/{made['id']}",
                           headers=provider["auth"])
    assert theirs.status_code == 404, "another account deleted somebody's row"

    mine = client.delete(f"/api/pounds/{made['id']}", headers=booking["auth"])
    assert mine.status_code == 200
    assert mine.get_json()["summary"]["spentPence"] == 0


def test_one_ledger_per_account(client, booking, provider):
    auth_post(client, booking, spentOn=FRIDAY, description="Theirs",
              cadCents=5000)
    others = client.get("/api/pounds", headers=provider["auth"]).get_json()
    assert others["conversions"] == []
    assert others["spentPence"] == 0


def test_the_whole_ledger_needs_a_token(client):
    for call in (client.get("/api/pounds"),
                 client.post("/api/pounds", json={}),
                 client.get("/api/pounds/quote?cadCents=100&on=" + FRIDAY),
                 client.delete("/api/pounds/1")):
        assert call.status_code in (401, 403), (
            "an endpoint on somebody's own ledger answered without a token")


# ------------------------------------------------------------ the refusals


def test_parsing_a_rate_with_no_point_and_with_nothing():
    from domain import pounds
    assert pounds._parts("20") == (20, 0)
    assert pounds._parts("1.6064") == (16064, 4)
    assert pounds._parts("-0.5") == (-5, 1)
    with pytest.raises(pounds.PoundError):
        pounds._parts("   ")


def test_a_date_arrives_in_any_of_its_shapes():
    """The wire sends strings, the database sends strings, and callers hold
    dates. All three have to land on the same day."""
    import datetime as dt
    from domain import pounds
    assert pounds._as_date("2026-09-11") == dt.date(2026, 9, 11)
    assert pounds._as_date(dt.date(2026, 9, 11)) == dt.date(2026, 9, 11)
    assert pounds._as_date(dt.datetime(2026, 9, 11, 17, 30)) == dt.date(2026, 9, 11)


def test_a_rate_file_with_junk_in_it_keeps_the_rows_it_can_read(tmp_path):
    """A row with no date, and a rate that is not a number, are skipped
    rather than taking the whole file down with them."""
    from domain import pounds
    path = tmp_path / "legs.csv"
    path.write_text(
        "date,CAD,GBP\n"
        ",1.60,0.85\n"                 # no date
        "2026-09-11,1.6064,0.85815\n"
        "2026-09-10,not-a-number,0.859\n",
        encoding="utf-8")
    try:
        table = pounds.load(path=str(path), force=True)
        assert "2026-09-11" in table
        assert "" not in table
        assert "CAD" not in table["2026-09-10"]
    finally:
        pounds.reset()


def test_a_rate_file_with_no_rates_is_refused(tmp_path):
    from domain import pounds
    path = tmp_path / "empty.csv"
    path.write_text("date,CAD,GBP\n", encoding="utf-8")
    try:
        with pytest.raises(pounds.PoundError):
            pounds.load(path=str(path), force=True)
    finally:
        pounds.reset()


def test_a_date_with_nothing_within_ten_days_is_refused(ctx):
    """A Saturday far past the newest rate gets past the "a rate is still
    coming" check and then finds nothing to walk back to."""
    from domain import pounds
    with pytest.raises(pounds.PoundError) as raised:
        pounds.quote(10000, "2027-01-02")       # a Saturday
    assert "within" in str(raised.value)


def test_a_negative_markup_is_refused_in_both_directions(ctx):
    from domain import pounds
    cad, gbp, _on = pounds.legs(FRIDAY)
    with pytest.raises(pounds.PoundError):
        pounds.to_pounds(100000, cad, gbp, fee_bp=-1)
    with pytest.raises(pounds.PoundError):
        pounds.from_pounds(50000, cad, gbp, fee_bp=-1)


def test_a_published_rate_of_zero_is_refused(ctx):
    from domain import pounds
    with pytest.raises(pounds.PoundError):
        pounds.to_pounds(100000, (0, 0), (85815, 5))


def test_a_row_whose_date_lost_its_rate_says_so_instead_of_counting_zero(
        client, booking, ctx):
    """A stored row is only dollars and a date. If the rate file later stops
    covering that date, the row must say it cannot be converted rather than
    contribute nothing silently and quietly shrink the total."""
    from core import database as db
    from domain import pounds

    db.insert(
        """INSERT INTO pound_conversions
           (user_id, spent_on, description, category, cad_cents)
           VALUES (?, ?, ?, ?, ?)""",
        (booking["user"]["id"], "2027-01-02", "Later than the file", None,
         50000))

    listed = client.get("/api/pounds", headers=booking["auth"]).get_json()
    assert len(listed["conversions"]) == 1
    assert "error" in listed["conversions"][0], listed["conversions"][0]
    assert "pence" not in listed["conversions"][0]
    assert listed["spentPence"] == 0
    assert pounds.spent(booking["user"]["id"]) == 0


# -------------------------------------------------------------- the quote


def test_a_quote_costs_nothing_and_records_nothing(client, booking):
    got = client.get(f"/api/pounds/quote?cadCents=100000&on={FRIDAY}",
                     headers=booking["auth"])
    assert got.status_code == 200
    quote = got.get_json()["quote"]
    assert quote["cadCents"] == 100000
    assert quote["feePence"] > 0
    assert quote["referencePence"] > quote["pence"], (
        "the markup should leave you with less than the reference rate")
    assert quote["fits"] is True
    assert quote["rateDate"] == FRIDAY

    listed = client.get("/api/pounds", headers=booking["auth"]).get_json()
    assert listed["conversions"] == [], "a quote recorded something"


def test_a_quote_says_when_it_would_not_fit(client, booking):
    """The page has to say "that would put you over" before the button is
    pressed, not after the request comes back refused."""
    auth_post(client, booking, spentOn=FRIDAY, description="Rent",
              cadCents=180000)
    got = client.get(f"/api/pounds/quote?cadCents=100000&on={FRIDAY}",
                     headers=booking["auth"]).get_json()["quote"]
    assert got["fits"] is False
    assert got["remainingPence"] < got["pence"]


def test_a_quote_refuses_an_amount_it_cannot_read(client, booking):
    for query in ("cadCents=&on=" + FRIDAY, "cadCents=lots&on=" + FRIDAY,
                  "cadCents=-500&on=" + FRIDAY, "cadCents=100&on=nonsense"):
        got = client.get(f"/api/pounds/quote?{query}",
                         headers=booking["auth"])
        assert got.status_code == 400, f"{query} was accepted"
